### ISSUE TITLE
关于这样工程代码冗余问题

### ISSUE THREAD

**Issue by WM520** [lixiang1994/LEETheme#1]
楼主可以用黑魔法把设置控件的代码,封装到各自控件的类别里,建议O(∩_∩)O哈哈~

**Comment by lixiang1994** [comment]
你说的黑魔法是 Method Swizzling 吗? 这个我内部有用到的 , 用来解决dealloc释放的问题 , 我的内部原理就是为每一个添加设置的对象 关联一个model , 这个model中记录了这个对象的设置信息 , 在触发主题设置时 根据该对象的model中的信息 进行相应的设置 , 你所说的封装到各自控件的类别中 , 其实我最初的版本就是这样做的,  每个控件的category都有 , 但是后来会发现其实没有比较所有控件都去做category , 只需要处理个别的控件 以及 直接在NSObject的category中处理设置就可以了 ,  我应该是从1.0.3版本开始改进了内部的处理机制 , 直接砍掉了1000多行多余的代码

**Comment by lixiang1994** [comment]
你可以看一下最新的版本 利用KVC去处理属性的设置 , 2中模式的常规属性设置都是这样的 , 不过button这种非属性的设置 我还在考虑如何优化到最好 , 如果你有什么好的建议 希望多多提出哈

**Comment by WM520** [comment]
感谢解惑
