### ISSUE TITLE
使用这个库之后，会不定时的Crash

### ISSUE THREAD

**Issue by 200895045** [lixiang1994/LEETheme#12]
新建的测试项目，导入这个库文件之后，我只是在delegate中设置了默认主题（[LEETheme defaultTheme:DAY];）
然后添加了Demo中 LEEBubble 相关的代码，什么都不做，过段时间应用就crash掉了，重现了4、5次。

**Comment by lixiang1994** [comment]
您好 方便的话请加一下QQ 332459523, 将测试项目发给我看一下

**Comment by lixiang1994** [comment]
@200895045

**Comment by qiaoyan** [comment]
你们联系上没有？

**Comment by lixiang1994** [comment]
没加我 @qiaoyan  你遇到什么问题了吗
