### ISSUE TITLE
关于开源协议

### ISSUE THREAD

**Issue by haifenghuang** [lixiang1994/LEETheme#19]
hi， 你好：
    这个软件使用的是GPL V3开源协议，那么问题来了，使用你这个开源库的用户，他们必须将自己的软件也开源。这个对于一些小公司或者个人来说，可能不是很合适。

   我的意思是，如果使用了你的代码库的个人或者公司，想对你的代码做一定的定制，那么必须将自己的软件也开源。

**Comment by lixiang1994** [comment]
感谢提醒, 这个项目开源时间比较早 当时没有太在意协议问题, 我近期会改为MIT

**Comment by lixiang1994** [comment]
已更改完成
