### ISSUE TITLE
pod

### ISSUE THREAD

**Issue by Arise903** [lixiang1994/LEETheme#20]
pod 'LEETheme', '~> 1.1.8' 下载下来的是1.1.7版本， 还有        return weakSelf.LeeAddKeyPathAndValue(tag , @"_placeholderLabel.textColor" , color); 程序运行会在这个地方崩溃是什么原因？？

**Comment by lixiang1994** [comment]
pod版本配置错了, 今晚我重新发布一下.
_placeholderLabel.textColor的问题是iOS13不允许使用KVC访问私有属性的问题, 我会尽快适配的.
感谢你的反馈 Thanks♪(･ω･)ﾉ

**Comment by Arise903** [comment]
合作共赢，毕竟你的框架为我们开发节约了大量的时间。

**Comment by lixiang1994** [comment]
@lilovexin pod已更新1.1.9, 我这边网络有点差 折腾了一天才推上去
