### ISSUE TITLE
改变tabBar或者navigationBar的tintColor无法改变图片的颜色

### ISSUE THREAD

**Issue by ylxieg** [lixiang1994/LEETheme#21]
图片渲染用UIImageRenderingModeAlwaysTemplate模式，可是无法根据navigationBar.lee_theme
    .LeeAddBarTintColor或者tabBar.lee_theme
    .LeeAddBarTintColor的颜色而改变是为什么呀

**Comment by lixiang1994** [comment]
可以发一下相关代码截图吗




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2019年08月20日 09:38，Matt 写道：

图片渲染用UIImageRenderingModeAlwaysTemplate模式，可是无法根据navigationBar.lee_theme
.LeeAddBarTintColor或者tabBar.lee_theme
.LeeAddBarTintColor的颜色而改变是为什么呀

**Comment by ylxieg** [comment]
给你这个18611401994@163.com邮箱发邮件啦大神

**Comment by lixiang1994** [comment]
```
    self.tabBar.lee_theme
    .LeeAddTintColor(DAY , LEEColorRGB(255, 255, 255))
    .LeeAddTintColor(NIGHT , LEEColorRGB(40, 40, 40))
```
使用`TintColor`而不是`BarTintColor`

**Comment by lixiang1994** [comment]
`TintColor` 可以修改图片颜色, 如果是背景颜色修改则用`BarTintColor ` (iOS7以上)

**Comment by ylxieg** [comment]
嗯。可以了。谢谢
