### ISSUE TITLE
这种换肤、主题切换个人觉得有些问题

### ISSUE THREAD

**Issue by liujunliuhong** [lixiang1994/LEETheme#22]
![image](https://user-images.githubusercontent.com/16097707/81160827-2cb6f480-8fbd-11ea-86b3-4782d6d23e0b.png)
这种设置方式，代码不会报错，但是运行会崩溃，看了下源码，所有属性其实都在```LEEThemeConfigModel```里面，也就是说任意```NSObject```对象都能调用，没有做限制区分

**Comment by lixiang1994** [comment]
嗯嗯, 这个问题我思考过, 为了通用性 我没有设计做类型上的限制, 但保持了和原本属性名称一致,  所以需要开发者自己控制该调用什么属性, 有利有弊, 近期我考虑抽时间做一下类型划分.

**Comment by lixiang1994** [comment]
其实成本很大的, 不同类型可能有相同的属性 这样我就要写N * N份

**Comment by liujunliuhong** [comment]
考虑用继承吧，把`LEEThemeConfigModel `当做基类

**Comment by lixiang1994** [comment]
我说的就是用继承写, 不用继承 那真是灾难了.
