### ISSUE TITLE
跟随系统主题有点问题

### ISSUE THREAD

**Issue by yxx19950523** [lixiang1994/LEETheme#23]
当我APP是浅色的时候，我去显示与亮度换成深色，然后上划切换程序，不会变黑，要进入APP了才会变黑，微信上划切换的时候就已经变成了黑色

**Comment by yxx19950523** [comment]
然后就是我杀死APP，切换深色，点击APP进去还是白色

**Comment by lixiang1994** [comment]
第一个问题 似乎没法解决, 进入后台后 整个进程被挂起了, 没法执行主题变化的代码, 系统提供的适配方案可以 是因为在进入后台后 系统会截取当前window黑白主题的两种图, 所以你可以看到切换后微信随之变化, 其实微信的进程也一样是挂起的, 但是系统去做了更换截图的操作.

第二个问题, 我已经在demo中加了示例, 原理就是启动时主动同步一下当前系统主题对应的主题就可以了, 下载最新demo 在MainWindow.m中可以看到.

**Comment by yxx19950523** [comment]
作者你好，能详谈吗，给个联系方式，我已经解决了，希望能告诉你详细的方法，然后更新一下，或者加一下我，我的QQ:569907876

**Comment by lixiang1994** [comment]
呀？好的




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年05月16日 12:04，yxx19950523 写道：

作者你好，能详谈吗，给个联系方式，我已经解决了，希望能告诉你详细的方法，然后更新一下，或者加一下我，我的QQ:569907876

**Comment by lixiang1994** [comment]
原因记录:

系统原理如我之前所说, 进入后台时 会调用主题切换`- (void)traitCollectionDidChange:(UITraitCollection *)previousTraitCollection` 并且得到2个主题的截图,  当用户切换系统主题时, 系统切换不同截图. 
这个截图过程在本次Runloop下完成.
而内部有一个dispatch_main_queue的async.
实际上确实切换了主题 但是因为async 所以会在下一次Runloop完成切换, 但是系统的截图操作早已经进行了, 所以一直无法看到变化.

当时出于线程安全考虑 所以加了async.
现在想想没有必要, UI操作就应该在主线程, 切换主题也是一样, 所以这个async其实比较多余.
