### ISSUE TITLE
iOS8.4 要崩溃

### ISSUE THREAD

**Issue by bolan9999** [lixiang1994/LEETheme#5]
NSObject (LEEThemeConfigObject)交换方法的时候有问题，lee_dealloc根本没有交换到NSObject里面的方法，而是某个子类的dealloc，实际情况其实是lee_dealloc根本从来就没执行，通知永远没有被移除，在iOS8.4上如果有重用Cell的情况会崩溃。将交换的class改成NSObject就好了。

**Comment by lixiang1994** [comment]
你确定没有交换到? 我这里断点调试没有问题, 而且iOS8.4运行我的demo也没出现崩溃, 你能否发几个截图或者详细描述一下你使用的情景,这样可以更好定位问题

**Comment by bolan9999** [comment]
所有版本的系统断点都走不进lee_dealloc，只是8.4系统没有移除通知崩溃了。 我断点查了，交换方法的时候，load方法里面self的真实类型根本不是NSObject，而是一个子类

**Comment by bolan9999** [comment]
![Uploading WX20170412-153326@2x.png…]()

**Comment by bolan9999** [comment]
上传不了图片，我在你的交换那里加了句打印
NSLog(@"system version = %.2f, [self class] = %@", [[UIDevice currentDevice].systemVersion floatValue], [self class]);
控制台的结果是：
system version = 10.20, [self class] = SSDKContext， 根本不是NSObject
