### ISSUE TITLE
tab的颜色好像更改不了呀

### ISSUE THREAD

**Issue by Jacky-LinPeng** [lixiang1994/LEETheme#6]

**Comment by lixiang1994** [comment]
可以啊 你没设置对吧 , 我这几天会更新新版本 demo也会完善很多 , 不急的话 你可以等等 , 现在我还在测试

**Comment by lixiang1994** [comment]
tabbar? 还是? tabbar的话 可以这样设置 , 你描述具体点 我告诉你怎么正确的设置

```
tabBar.lee_theme
.LeeAddBarTintColor(DAY , LEEColorRGB(255, 255, 255))
    .LeeAddBarTintColor(NIGHT , LEEColorRGB(40, 40, 40))
```

**Comment by Jacky-LinPeng** [comment]
哇！看到你还在更新！怒赞一个！你这个框架写的很赞！
问题：
修改主题 对应的修改tabitem上的文字颜色 与 icon的图片，这个好像还不行吧，

**Comment by Jacky-LinPeng** [comment]
tabBar.lee_theme
.LeeAddBarTintColor(DAY , LEEColorRGB(255, 255, 255))
    .LeeAddBarTintColor(NIGHT , LEEColorRGB(40, 40, 40))
这个是修改整条tabbar的背景色  
但是 我的问题是 要修改tabbar上的每个item的选中时候的字体颜色

**Comment by lixiang1994** [comment]
这样啊 , item设置的方式有很多 , 你不妨参考一下我的最新demo

**Comment by Jacky-LinPeng** [comment]
太感谢了！！！！

**Comment by lixiang1994** [comment]
客气

**Comment by Jacky-LinPeng** [comment]
有个建议：你的LeeTheme里面用到的 YYKit的 Dictionary+Add的 一个扩展方法：containsObjectForKey，建议修改一下

**Comment by lixiang1994** [comment]
谢谢提醒, 还有其他的地方用到其他库的方法了吗?

**Comment by lixiang1994** [comment]
已经去掉了 , 你目前使用有没有发现什么bug? 我这边已经测试完了 你如果也没有问题 我就发布pods了

**Comment by Jacky-LinPeng** [comment]
哈  其他的没发现什么  我要多向你学习 嘿嘿

**Comment by lixiang1994** [comment]
😁 互相学习
