### ISSUE TITLE
tableHeaderView 的颜色如何设置??

### ISSUE THREAD

**Issue by Arise903** [lixiang1994/LEETheme#7]
tableHeaderView 的颜色如何设置??

**Comment by Arise903** [comment]
我搞定了,解决了.以下是解决方法
-(void)tableView:(UITableView *)tableView willDisplayHeaderView:(nonnull UIView *)view forSection:(NSInteger)section{
    UITableViewHeaderFooterView *footer = (UITableViewHeaderFooterView *)view;
    footer.contentView.lee_theme
    .LeeAddBackgroundColor(DAY , [UIColor colorWithWhite:0.846 alpha:1.000])
    .LeeAddBackgroundColor(NIGHT , [UIColor colorWithRed:0.358 green:0.362 blue:0.362 alpha:1.000]);;
}

**Comment by lixiang1994** [comment]
😁 tableHeaderView其实就是UIView  UIView怎么设置 它就怎么设置 , 不过不建议你放到这个代理方法中 因为它会频繁被调用 , 其实你只需要设置一次就够了 多次设置反而浪费资源

**Comment by Arise903** [comment]
这么写吗??我之前是这么设置的,但是会在这地方崩溃,没办法我才写到了代理的方法里面.
    self.tableView.tableHeaderView.lee_theme
    .LeeAddBackgroundColor(DAY , [UIColor colorWithWhite:0.846 alpha:1.000])
    .LeeAddBackgroundColor(NIGHT , [UIColor colorWithRed:0.358 green:0.362 blue:0.362 alpha:1.000]);

**Comment by lixiang1994** [comment]
如果是我 我可能会新创建一个UITableViewHeaderFooterView子类 然后在初始化后设置一下主题 , 当然怎么写都没错 如果你UITableViewHeaderFooterView这个类可以满足你的需求 也不用建新的
